### ISSUE TITLE
After git diff, can't see what I'm typing.

### ISSUE THREAD

**Issue by meendoo** [git/git-scm.com#881]
Hi guys,

I'm using **bash version 2.10.1 for windows**. Every time I exit `git diff` I can't see what I'm typing.
It's not blocked or anything, cause I'm able to press enter after writing something and I get a response.

On the screenshot below I typed 4 random commands after it:
`git status`, `anything`,  `test` and `typing`.

Couldn't find a similar issue here.
Cheers.

![image 025](https://cloud.githubusercontent.com/assets/3496704/19893846/cf3b7174-a031-11e6-8e8a-b477f70418b1.jpg)

**Comment by meendoo** [comment]
Ok, just noticed that it's a problem that happens only when I leave with `CTRL+C`

**Comment by Rushi98** [comment]
Now that problem is solved. You can mark this issue `resolved`.

**Comment by peff** [comment]
This is the bug tracker for the git-scm.com website, not git itself. If you want to discuss further, the best venue is probably the [Git for Windows](https://github.com/git-for-windows/git) issue tracker. Though it really sounds like it is a problem of the pager (usually `less`) not restoring the terminal when it is interrupted by `^C`.

**Comment by Nallefjant** [comment]
Not solved.

**Comment by ttaylorr** [comment]
> Not solved.

@Nallefjant, I'm sorry that you're still encountering some issues. @peff notes above that this is the bug tracker for git-scm.com the website, not `git` the tool itself. If you're having problems, perhaps the best place to send them would be on git@vger.kernel.org, or the Git for Windows issue tracker.

**Comment by pedrorijo91** [comment]
this actually seems more of a git-for-windows problem.

Git for windows problems should be raised in [https://github.com/git-for-windows/git](https://github.com/git-for-windows/git)
